name: Run Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8'
          cache: true
          modules: 'qtimageformats qttools'

      - name: Configure CMake
        run: cmake -B build -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build
